[Dataset info]
split_ratio = 0.8
look_forward = 10
look_back = 70

[Shapes]
x_train = (57057, 70, 8)
y_train = (57057, 1)
x_test = (14185, 70, 8)
y_test = (14185, 1)

[Train info]
epochs = 1
validation_split = 0.1
batch_size = 128

[Prediction info]
batch_size = 128

